name: Compliance Scan

on:
  push:
    branches:
      - main

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Checkov
        run: pip install checkov

      - name: Run Terraform scan
        run: checkov -d terraform
